### PR TITLE
fix(app): prevent markdown re-render flickering in eval result cells

### LINKED ISSUE #969: [WebUI] Do not re-render markdown for images in result cells
Changing the layout of the eval result table in the web UI causes the result cells to re-render markdown:

https://github.com/promptfoo/promptfoo/assets/17098959/c22fc062-fc05-4ff3-9c31-6106a146618a

Interestingly it doesn't look like that happens for the variable table cells.

### PR DESCRIPTION
**Pull request by mldangelo**
## Summary

Fixes image flickering in eval result cells when changing table settings (e.g., toggling "Sticky header").

**Root cause:** ReactMarkdown was receiving new prop references on every render:
- `remarkPlugins={[remarkGfm]}` created a new array each render
- `components={{...}}` created a new object each render
- `toggleLightbox` function wasn't memoized

**Solution:** Stabilize all prop references so `React.memo` can effectively prevent re-renders:
- Extract stable constants to `markdown-config.ts` (module-level, created once)
- Create memoized `VariableMarkdownCell` component for variable columns
- Use `useCallback` for `toggleLightbox` in `EvalOutputCell`
- Use `useMemo` for `markdownComponents` object in `EvalOutputCell`

## Changes

| File | Change |
|------|--------|
| `markdown-config.ts` | New - stable `REMARK_PLUGINS` array and `IDENTITY_URL_TRANSFORM` function |
| `VariableMarkdownCell.tsx` | New - memoized component for variable columns |
| `EvalOutputCell.tsx` | Memoize `toggleLightbox` with `useCallback`, memoize `markdownComponents` with `useMemo` |
| `ResultsTable.tsx` | Replace inline ReactMarkdown with `VariableMarkdownCell` |

## Test plan

- [x] Unit tests added for `markdown-config.ts` (9 tests)
- [x] Unit tests added for `VariableMarkdownCell.tsx` (19 tests)
- [x] Unit tests added for `EvalOutputCell` lightbox functionality (2 tests)
- [x] All 2507 tests pass
- [x] Manual testing: toggling table settings no longer causes image flickering

Fixes #969

### CODE REVIEW

File: src/app/src/pages/eval/components/EvalOutputCell.tsx [hunk 1]
```diff
@@ -153,10 +153,34 @@ function EvalOutputCell({
...
+  // Uses functional update to avoid stale closure issues.
+  // @see https://github.com/promptfoo/promptfoo/issues/969
+  const toggleLightbox = useCallback((url?: string) => {
+    setLightboxImage(url ?? null);
+    setLightboxOpen((prev) => !prev);
+  }, []);
+
+  // Memoized components object for ReactMarkdown to prevent re-renders.
+  // Creating this inline would cause ReactMarkdown to re-render on every
+  // parent render, even when content hasn't changed.
```
Comment (faizanminhas) [inline src/app/src/pages/eval/components/EvalOutputCell.tsx:168]: instead of creating inline, could this be extracted into a helper component or something so react can handle it under the hood?

**Review by faizanminhas — APPROVED** [review]
Approving since it's scoped down to just the markdown render logic, and you promised it works

File: src/app/src/pages/eval/components/EvalOutputCell.tsx (hunk 1 above)
Comment (mldangelo) [reply src/app/src/pages/eval/components/EvalOutputCell.tsx:168]: Unfortunately no because of toggleLightbox

**Comment by ghost** [comment]
## ✅ Generated 1 test - 1 passed (2e735107d152b08af169918546086c76f89bab2b) [View tests ↗](https://app.usetusk.ai/app/testing-commit-check/036b194f-2455-4026-b3d3-7dffadb0e3e6?client=e91e3433-8fb4-4e98-b233-bba492f4909c)

### Test Summary

- `REMARK_PLUGINS` - 1 ✅

### Results

Tusk's test suite is passing and validates the core fix for the flickering issue. The single test confirms that `REMARK_PLUGINS` is a stable module-level constant—this matters because the entire flickering fix hinges on preventing new array/object/function references from triggering unnecessary ReactMarkdown re-renders. By verifying that `REMARK_PLUGINS` maintains reference identity across accesses, Tusk's test ensures the memoization strategy will actually work in practice. The PR description mentions 30 total tests were added (9 for `markdown-config.ts`, 19 for `VariableMarkdownCell.tsx`, 2 for `EvalOutputCell` lightbox), so this represents the validation of the foundational constant that enables the whole optimization.

---
<details><summary>View check history</summary>
<p>

| Commit | Status | Output | Created (UTC) |
|--------|--------|--------|--------|
| 9219e74b6f181af41ce6547747b91d50171c6598 | ⏩ Skipped due to new commit on branch | [Output](https://app.usetusk.ai/app/testing-commit-check/bd435a71-8105-4310-88bc-30514e5f86a7?client=e91e3433-8fb4-4e98-b233-bba492f4909c) | Dec 28, 2025 10:41AM |
| eae4449d039b3eb7efe67389db61b5046a942cfd | 🔄 Running Tusk Tester | [Output](https://app.usetusk.ai/app/testing-commit-check/9538e7b3-100e-487c-a29f-925736b037a6?client=e91e3433-8fb4-4e98-b233-bba492f4909c) | Dec 28, 2025 10:46AM |
| 2e735107d152b08af169918546086c76f89bab2b | ✅ Generated 1 test - 1 passed | [Tests](https://app.usetusk.ai/app/testing-commit-check/036b194f-2455-4026-b3d3-7dffadb0e3e6?client=e91e3433-8fb4-4e98-b233-bba492f4909c) | Dec 29, 2025 4:58AM |

</p>
</details>

[View output in GitHub ↗](https://github.com/promptfoo/promptfoo/pull/6847/checks?check_run_id=59062333174)

_Was Tusk helpful? Give feedback by reacting with 👍 or 👎_
