### PR TITLE
fix: prioritize tool calls over content in openrouter provider

### LINKED ISSUE #5262: Unable to disable thinking for qwen3-235b-a22b-thinking-2507
**Describe the bug**
Similar to https://github.com/promptfoo/promptfoo/issues/5182

All my function call assertions fail because I am unable to suppress the thinking output of qwen3-235b-a22b-thinking-2507

When trying to use qwen/qwen3-235b-a22b-thinking-2507 I am unable to suppress thinking by using the `showThinking: false` flag as the Promptfoo docs describe

Is there really no other choice than using qwen/qwen3-235b-a22b-2507? I would rather use the general thinking model 

**To Reproduce**
Use this as a provider to reproduce

- id: openrouter:qwen/qwen3-coder
    config:
      temperature: 0.1
      showThinking: false
      top_p: 0.25
      tool_choice: auto
      apiKeyEnvar: OPENROUTER_API_KEY
      apiBaseUrl: https://openrouter.ai/api/v1
      tools: *tools
`;

**Expected behavior**
Thinking output should be suppressed--only a tool call should be visible if triggering a tool call

**Screenshots**

NA

**System information:**

=============================================================================================
Promptfoo Debug Information
=============================================================================================
{
  "version": "0.117.5",
  "platform": {
    "os": "darwin",
    "release": "24.6.0",
    "arch": "arm64",
    "nodeVersion": "v20.18.1"
  },
  "env": {},
  "configInfo": {
    "configExists": false,
    "configContent": null
  }
}
=============================================================================================
Please include this output when reporting issues on GitHub: https://github.com/promptfoo/promptfoo/issues

- Promptfoo version:

0.117.5

**Additional context**
NA

### PR DESCRIPTION
**Pull request by mldangelo**
## Summary
Fixes OpenRouter provider logic to properly handle  for thinking models that return content + reasoning + tool_calls.

## Problem
- Issue #5262:  ignored 
- Users received thinking content instead of tool calls
- Function call assertions failed consistently

## Root Cause
Logic prioritized  over , causing tool calls to be ignored when all three fields were present.

## Solution
- Reorder logic to check  first, then , then 
- Tool calls now always take priority and never include thinking content
-  properly respected across all scenarios

## Testing
- ✅ 23 unit tests pass (added 2 new edge case tests)
- ✅ End-to-end validation with affected models
- ✅ No regressions on existing functionality
- ✅ Verified with Qwen, Gemini, and OpenAI models

## Changes
- Modified : Reordered conditional logic
- Updated : Added comprehensive test coverage

Resolves #5262

### CODE REVIEW

**Comment by faizanminhas** [comment]
this is not consistent with the openai chat provider btw https://github.com/promptfoo/promptfoo/blob/7338bd0d623ad7a78cbe7d2bdf4aba36a7097205/src/providers/openai/chat.ts#L385-L401

File: src/providers/openrouter.ts [hunk 1]
```diff
@@ -116,18 +116,21 @@ export class OpenRouterProvider extends OpenAiChatCompletionProvider {
...
-    // Prioritize content over reasoning
+    // Prioritize tool calls over content and reasoning
     let output = '';
-    if (message.content && message.content.trim()) {
+    const hasFunctionCall = !!(message.function_call && message.function_call.name);
+    const hasToolCalls = Array.isArray(message.tool_calls) && message.tool_calls.length > 0;
+    if (hasFunctionCall || hasToolCalls) {
+      // Tool calls always take priority and never include thinking
+      output = hasFunctionCall ? message.function_call : message.tool_calls;
+    } else if (message.content && message.content.trim()) {
```
Comment (sklein12) [inline src/providers/openrouter.ts:126]: why don't we merge it all together?
