### PR TITLE
fix(provider): OpenAI Realtime history issue

### LINKED ISSUE #3471: Openai realtime api doesn't seem to support history.
**Describe the bug**

Passing messages history to realtime api doesn't seem to work at all (even in example from https://github.com/promptfoo/promptfoo/blob/main/examples/openai-realtime/promptfooconfig-conversation.yaml); realtime seems to ignore previous conversation.

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1) npx promptfoo@latest init --example openai-realtime
2) cd .\openai-realtime\
3) npx promptfoo eval -c promptfooconfig-conversation.yaml
4) Get result showing conversation doesn't seem to be propagated. 

Image

Looking at generated prompt field, it seems wrong (this is prompt from the 2nd turn of a sample conversation):

`[
  {
    "prompt": [
      {
        "role": "system",
        "content": [
          {
            "type": "input_text",
            "text": "You are a helpful, friendly AI assistant. Keep your responses conversational and engaging."
          }
        ]
      },
      {
        "role": "user",
        "content": [
          {
            "type": "input_text",
            "text": "What are some popular tourist destinations in Japan?"
          }
        ]
      }
    ],
    "input": [
      {
        "type": "input_text",
        "text": "What are some popular tourist destinations in Japan?"
      }
    ],
    "output": "Some popular tourist destinations in Japan include:\n\n1. Tokyo - The bustling capital city known for its modern architecture, shopping districts, and cultural landmarks like the Meiji Shrine and Tokyo Tower.\n2. Kyoto - Famous for its well-preserved temples, traditional wooden houses, and beautiful gardens, including the Fushimi Inari Shrine and Kinkaku-ji (Golden Pavilion).\n3. Osaka - Known for its vibrant nightlife, street food, and attractions like Osaka Castle and Universal Studios Japan.\n4. Hiroshima - Home to the Peace Memorial Park and Museum, and the iconic Itsukushima Shrine on Miyajima Island.\n5. Nara - Renowned for its historic temples like Todai-ji, famous for its giant Buddha statue, and friendly deer roaming in Nara Park.\n6. Mount Fuji - Japan's highest peak, offering stunning views and popular hiking trails.\n7. Hokkaido - Known for its natural beauty, ski resorts, and national parks like Shiretoko and Daisetsuzan.\n8. Okinawa - A group of tropical islands known for their beautiful beaches, coral reefs, and unique Ryukyuan culture."
  },
  {
    "prompt": [
      {
        "role": "system",
        "content": [
          {
            "type": "input_text",
            "text": "You are a helpful, friendly AI assistant. Keep your responses conversational and engaging."
          }
        ]
      },
      {
        "role": "user",
        "content": [
          {
            "type": "input_text",
            "text": [
              {
                "type": "input_text",
                "text": "What are some popular tourist destinations in Japan?"
              }
            ]
          }
        ]
      },
      {
        "role": "assistant",
        "content": [
          {
            "type": "text",
            "text": "Some popular tourist destinations in Japan include:\n\n1. Tokyo - The bustling capital city known for its modern architecture, shopping districts, and cultural landmarks like the Meiji Shrine and Tokyo Tower.\n2. Kyoto - Famous for its well-preserved temples, traditional wooden houses, and beautiful gardens, including the Fushimi Inari Shrine and Kinkaku-ji (Golden Pavilion).\n3. Osaka - Known for its vibrant nightlife, street food, and attractions like Osaka Castle and Universal Studios Japan.\n4. Hiroshima - Home to the Peace Memorial Park and Museum, and the iconic Itsukushima Shrine on Miyajima Island.\n5. Nara - Renowned for its historic temples like Todai-ji, famous for its giant Buddha statue, and friendly deer roaming in Nara Park.\n6. Mount Fuji - Japan's highest peak, offering stunning views and popular hiking trails.\n7. Hokkaido - Known for its natural beauty, ski resorts, and national parks like Shiretoko and Daisetsuzan.\n8. Okinawa - A group of tropical islands known for their beautiful beaches, coral reefs, and unique Ryukyuan culture."
          }
        ]
      },
      {
        "role": "user",
        "content": [
          {
            "type": "input_text",
            "text": "Which of those places is best to visit in autumn?"
          }
        ]
      }
    ],
    "input": [
      {
        "type": "input_text",
        "text": "Which of those places is best to visit in autumn?"
      }
    ],
    "output": "Some great places to visit in autumn include:\n\n1. New England in the USA for its stunning fall foliage.\n2. Kyoto, Japan, known for its beautiful autumn leaves.\n3. Bavaria, Germany, where you can experience traditional Oktoberfest celebrations.\n4. Tuscany, Italy, for its picturesque landscapes and harvest season.\n5. The Canadian Rockies, offering breathtaking scenery and fewer crowds.\n\nEach of these destinations offers something special during the autumn season."
  }
]`

**Expected behavior**
Openai can continue the conversation.

**Screenshots**

**System information:**

If possible, please output the results of `promptfoo debug` and paste the output here.

- Promptfoo version: 0.107.4

**Additional context**

The similar behavior is present when I'm trying to write my tests (that include conversation so far)

### PR DESCRIPTION
**Pull request by AISimplyExplained**
### Changes
- Implemented persistent WebSocket connection handling to maintain conversation state
- Added tracking for message IDs and assistant responses to maintain conversation flow
- Optimized connection management with proper cleanup and timeout handling
- Added support for tracking conversation turns through `previousItemId` and `assistantMessageIds`
- Added `maintainContext: true` as the default configuration option in the OpenAI Realtime provider

### Related Issues
Closes #3471

### CODE REVIEW

File: src/commands/eval.ts [hunk 1]
```diff
@@ -530,6 +531,16 @@ export async function doEval(
     if (testSuite.redteam) {
       showRedteamProviderLabelMissingWarning(testSuite);
     }
+
+    // Clean up any WebSocket connections
+    if (testSuite.providers.length > 0) {
+      for (const provider of testSuite.providers) {
+        if (provider instanceof OpenAiRealtimeProvider) {
+          provider.cleanup();
```
Comment (mldangelo) [inline src/commands/eval.ts]: This is a great idea. We can add it as an optional method to api provider 

```suggestion
          provider?.cleanup();
```

File: src/commands/eval.ts [hunk 2]
```diff
@@ -530,6 +531,16 @@ export async function doEval(
     if (testSuite.redteam) {
       showRedteamProviderLabelMissingWarning(testSuite);
     }
+
+    // Clean up any WebSocket connections
+    if (testSuite.providers.length > 0) {
+      for (const provider of testSuite.providers) {
+        if (provider instanceof OpenAiRealtimeProvider) {
```
Comment (mldangelo) [inline src/commands/eval.ts]:
```suggestion
```

**Review by mldangelo — COMMENTED** [review]
This is great! Thank you @AISimplyExplained

File: src/commands/eval.ts (hunk 1 above)
Comment (mldangelo) [reply src/commands/eval.ts]: See https://github.com/promptfoo/promptfoo/blob/182e9af16a30202ef131cbec5a83ed4244f0dfdb/src/types/providers.ts#L75

File: src/providers/openai/realtime.ts [hunk 3]
```diff
@@ -72,6 +86,35 @@ export class OpenAiRealtimeProvider extends OpenAiGenericProvider {
...
+    this.currentAudioFormat = 'wav';
+    this.isProcessingAudio = false;
+    if (this.audioTimeout) {
+      clearTimeout(this.audioTimeout);
+      this.audioTimeout = null;
+    }
+  }
+
+  // Add method to handle audio processing timeout
+  private setupAudioTimeout(reject: (reason: Error) => void): void {
```
Comment (mldangelo) [inline src/providers/openai/realtime.ts]: @AISimplyExplained can you please take a quick look at this comment

File: src/commands/eval.ts [hunk 4]
```diff
@@ -530,6 +531,14 @@ export async function doEval(
     if (testSuite.redteam) {
       showRedteamProviderLabelMissingWarning(testSuite);
     }
+
+    // Clean up any WebSocket connections
```
Comment (mldangelo) [inline src/commands/eval.ts:549]:
```suggestion
```

File: src/commands/eval.ts [hunk 5]
```diff
@@ -530,6 +531,14 @@ export async function doEval(
...
+    if (testSuite.providers.length > 0) {
+      for (const provider of testSuite.providers as ApiProvider[]) {
```
Comment (mldangelo) [inline src/commands/eval.ts]: don't coerce here. You can use isApiProvider(..) instead

**Review by mldangelo — COMMENTED** [review]
This looks good! Please take a look at the comments. I bet we can get this in before standup!

**Review by mldangelo — APPROVED** [review]
Thank you!
