### PR TITLE
fix(eval): show more toggle for metrics in cells for evals

### LINKED ISSUE #7513: "Show More" button does not work on eval viewer
**Describe the bug**
The "Show More" button does not work on eval viewer. It's not clickable.

**To Reproduce**
Run an eval with more than 5 metrics, try clicking show more.

**Expected behavior**
For more metrics to show

**Screenshots**

Image

**System information:**

This occurs on web viewer and local

- Promptfoo version: 0.120.22

This is making our evals very difficult to see at a glance, would appreciate an urgent fix!

### PR DESCRIPTION
**Pull request by kkahadze**
## Summary
  - Implement the default inline expand/collapse behavior for the "Show more" button in `CustomMetrics` when no `onShowMore` callback is provided
  - The component's docstring already described this as the intended default, but it was never implemented — clicking "Show more" in eval output cells (EvalOutputCell) didn't do anything

  Closes #7513

  ## Test plan
  1. Create the following config
```yaml 
providers:
  - echo
prompts:
  - 'Write about {{topic}} covering safety, quality, performance, reliability, scalability, security, usability, accessibility, maintainability, portability, efficiency, and compliance.'
defaultTest:
  assert:
    - type: contains
      value: safety
      metric: Safety
    - type: contains
      value: quality
      metric: Quality
    - type: contains
      value: performance
      metric: Performance
    - type: contains
      value: reliability
      metric: Reliability
    - type: contains
      value: scalability
      metric: Scalability
    - type: contains
      value: security
      metric: Security
    - type: contains
      value: usability
      metric: Usability
    - type: contains
      value: accessibility
      metric: Accessibility
    - type: contains
      value: maintainability
      metric: Maintainability
    - type: contains
      value: portability
      metric: Portability
    - type: contains
      value: efficiency
      metric: Efficiency
    - type: contains
      value: compliance
      metric: Compliance
tests:
  - vars: { topic: 'web apps' }
  - vars: { topic: 'APIs' }
  - vars: { topic: 'databases' }
```
  2. Run `npm run local -- eval -c path/to/promptfooconfig.yaml`
  3. Open the eval in the web viewer (`npm run dev`)
  4. Scroll down until the header collapses
  5. Click on an individual result cell, you should see 10 metric pills and a "Show more..." button
  6. Click "Show more...", all 14 metrics should expand inline
  7. Click "Show less...", metrics should collapse back to 10
  8. Scroll up to the header row and click "Show more...", should still open the full metrics dialog (existing behavior
  unchanged)

### CODE REVIEW

File: src/app/src/pages/eval/components/CustomMetrics.tsx [hunk 1]
```diff
@@ -149,9 +152,9 @@ const CustomMetrics = ({
         <div
           className="show-more-toggle clickable"
           data-testid="toggle-show-more"
-          onClick={onShowMore}
+          onClick={onShowMore ?? (() => setShowAll(!showAll))}
         >
-          Show more...
+          {showAll ? 'Show less...' : 'Show more...'}
         </div>
```
Comment (faizanminhas) [inline src/app/src/pages/eval/components/CustomMetrics.tsx]: @claude should this be a button for accessibility?

File: src/app/src/pages/eval/components/CustomMetrics.tsx [hunk 2]
```diff
@@ -77,9 +79,10 @@ const CustomMetrics = ({
   const { data: cloudConfig } = useCloudConfig();
   const { config } = useTableStore();
   const policiesById = useCustomPoliciesMap(config?.redteam?.plugins ?? []);
+  const [showAll, setShowAll] = useState(false);
```
Comment (faizanminhas) [inline src/app/src/pages/eval/components/CustomMetrics.tsx]: nit: you should use a more descriptive name (i.e. `shouldTruncateMetrics` or something) since this is a little ambiguous
